### ISSUE TITLE
Migration file creates a hash column of 255, longer than what it actually needs

### ISSUE THREAD

**Issue by ringodingoflamingo** [ggoral/easy-passport-local-sequelize-express4-sample#1]
Hello, thanks a lot for the sample, it really helped me understanding more of the combination between sequelize, passport and express. I've got it to work using sqlite but not with postgresql. 

After a while i found out that the hash consists of 1024 character while the migration file (using hash: Sequelize.STRING) creates a VARCHAR(255) column. After changing this to 1050 (a bit more than 1024 just to be safe) it worked. Apparently it's possible to pass a parameter along for the length of the string (hash: Sequelize.STRING(1050)) but i haven't tried this. I just wanted to write this here so others could read up about it in case they have the same problem.

Thank you,

Ringo

**Comment by ggoral** [comment]
Hi @rinagonics, please take a look https://github.com/ggoral/try-passport-with-sequelize, because "passport-local-sequelize" is frozen for months and it isn't necessary.

Thanks all for your contribution,
Gonzalo.
