### ISSUE TITLE
App doesn't auth correctly when using MySQL in development

### ISSUE THREAD

**Issue by owendavies93** [ggoral/easy-passport-local-sequelize-express4-sample#2]
If I change config.json to look something like:

```
  "development": {
    "username": "user",
    "password": "pass",
    "database": "testdb",
    "host":     "127.0.0.1",
    "dialect":  "mysql"
  },
```

All attempts to authenticate a user fail, I get a 401 back from all auth requests.

I was writing my own app and experienced this, so cloned this repo to try it out, and saw exactly the same behaviour. Using sqlite works in both my app and this one.

To reproduce:
- clone the repo
- install mysql server and `npm install mysql`
- follow the instructions in the README to set up the app
- create the database to match the JSON snippet above
- register a user (appears to work fine) and attempt to log in

**Comment by ggoral** [comment]
@sirgraystar  

I've tried to copy this sample but without install 'passport-local-sequelize' package, because is not necessary, with a simple configuration file you can get the same result.

Please, take a look here https://github.com/ggoral/try-passport-with-sequelize

Best regards!
